/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EPbutton: typeof import('./components/EPcomponents/EPbutton.vue')['default']
    EPtable: typeof import('./components/EPcomponents/EPtable.vue')['default']
    EPtableV2: typeof import('./components/EPcomponents/EPtableV2.vue')['default']
    EPuploadImg: typeof import('./components/EPcomponents/EPuploadImg.vue')['default']
    GHeader: typeof import('./components/GlobalLayout/GHeader.vue')['default']
    GMain: typeof import('./components/GlobalLayout/GMain.vue')['default']
    GNav: typeof import('./components/GlobalLayout/GNav.vue')['default']
    GSlider: typeof import('./components/GlobalLayout/GSlider.vue')['default']
    GTable: typeof import('./components/GlobalLayout/GTable.vue')['default']
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    Index: typeof import('./components/GlobalLayout/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tips: typeof import('./components/MyComponents/Tips.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
